services:
  postgres:
    image: postgres:16
    container_name: oj-postgres
    environment:
      POSTGRES_DB: oj
      POSTGRES_USER: ojuser
      POSTGRES_PASSWORD: ******
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: oj-redis
    ports:
      - "6379:6379"

api:
    image: oj-api-image
    container_name: oj-api
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: oj
      DB_USER: ojuser
      DB_PASSWORD: tempPASS
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: unless-stopped

volumes:
  pgdata:
