services:
  postgres:
    image: postgres:16
    container_name: oj-postgres
    environment:
      POSTGRES_DB: oj
      POSTGRES_USER: ojuser
      POSTGRES_PASSWORD: tempPASS
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: oj-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api   # path to your API code with Dockerfile
      dockerfile: Dockerfile
    container_name: oj-api
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
        DATABASE_URL: postgres://ojuser:tempPASS@postgres:5432/oj?sslmode=disable
        REDIS_ADDR: redis:6379
        REDIS_PASSWORD: ""
        OJ_WORKDIR: /app/jobs
    restart: unless-stopped

volumes:
  pgdata:
